# http://stackoverflow.com/questions/9535945/how-to-make-urls-secure-on-gae-using-the-django-wsgi-builtin
# how to mix django with not django app

application: [APP_ID]
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
